name: cinemana
description: simple command line tool to watch movies and TV shows using cinemana services.
version: 0.1.0
repository: https://github.com/hasanpasha/cinemana_dart
environment:
  sdk: '>=2.19.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  http: ^0.13.5
  interact: ^2.2.0
  intl: ^0.17.0
  multiple_result: ^4.0.0
  retry: ^3.1.0